### ISSUE TITLE
image shuffle/shuffle-backend not found

### ISSUE THREAD

**Issue by Im-anhdc** [Shuffle/Shuffle#1272] opened 2023-11-19 13:52 UTC
**Describe the bug**
Error when start docker .yml with image shuffle/shuffle-backend not found.

I tried latest version, 1.3.0, 1.2.1 but still error

**Comment by frikky** [comment] 2023-11-19 17:07
Hey,

did you use the package here? shuffle/shuffle-backend may not, work as that would point to dockerhub. We got all of this on github.  https://github.com/Shuffle/Shuffle/pkgs/container/shuffle-backend

Full url required: ghcr.io/shuffle/shuffle-backend:1.3.0

**Comment by frikky** [comment] 2023-11-19 17:07
@0x0elliot could you fix dockerhub replication for these from the CI?

**Comment by 0x0elliot** [comment] 2023-11-19 17:24
sure. I will fix it in a few.

**Comment by Im-anhdc** [comment] 2023-11-20 02:07
Dear team,

This error not only the image backend but also fontend, orborus.
![image](https://github.com/Shuffle/Shuffle/assets/68783065/f3f07133-87fa-44cf-abbb-2c8cda45973e)

**Comment by frikky** [comment] 2023-11-20 02:51
What are the full urls being used here @Im-anhdc? Please share your docker-compose.yml file

I just tried to pull this and it works totally fine: `ghcr.io/shuffle/shuffle-frontend:latest`

**Comment by Im-anhdc** [comment] 2023-11-20 03:03
```shell
[root@localhost Shuffle]# docker-compose pull
Pulling backend    ... pulling repository ghcr.io/shuffl...
Pulling frontend   ... pulling repository ghcr.io/shuffl...
Pulling orborus    ... pulling repository ghcr.io/shuffl...
Pulling opensearch ... done

ERROR: for frontend  Error: image shuffle/shuffle-frontend:latest not found

ERROR: for orborus  Error: image shuffle/shuffle-orborus:latest not found

ERROR: for backend  Error: image shuffle/shuffle-backend:latest not found
ERROR: Error: image shuffle/shuffle-backend:latest not found
[root@localhost Shuffle]# cat docker-compose.yml
version: '3'
services:
  frontend:
    image: ghcr.io/shuffle/shuffle-frontend:latest
    container_name: shuffle-frontend
    hostname: shuffle-frontend
    ports:
      - "${FRONTEND_PORT}:80"
      - "${FRONTEND_PORT_HTTPS}:443"
    networks:
      - shuffle
    environment:
      - BACKEND_HOSTNAME=${BACKEND_HOSTNAME}
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    image: ghcr.io/shuffle/shuffle-backend:latest
    container_name: shuffle-backend
    hostname: ${BACKEND_HOSTNAME}
    # Here for debugging:
    ports:
      - "${BACKEND_PORT}:5001"
    networks:
      - shuffle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SHUFFLE_APP_HOTLOAD_LOCATION}:/shuffle-apps:z
      - ${SHUFFLE_FILE_LOCATION}:/shuffle-files:z
    env_file: .env
    environment:
      #- DOCKER_HOST=tcp://docker-socket-proxy:2375
      - SHUFFLE_APP_HOTLOAD_FOLDER=/shuffle-apps
      - SHUFFLE_FILE_LOCATION=/shuffle-files
    restart: unless-stopped
  orborus:
    image: ghcr.io/shuffle/shuffle-orborus:latest
    container_name: shuffle-orborus
    hostname: shuffle-orborus
    networks:
      - shuffle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      #- DOCKER_HOST=tcp://docker-socket-proxy:2375
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - BASE_URL=http://${OUTER_HOSTNAME}:5001
      - DOCKER_API_VERSION=1.40
      - SHUFFLE_BASE_IMAGE_NAME=${SHUFFLE_BASE_IMAGE_NAME}
      - SHUFFLE_BASE_IMAGE_REGISTRY=${SHUFFLE_BASE_IMAGE_REGISTRY}
      - SHUFFLE_BASE_IMAGE_TAG_SUFFIX=${SHUFFLE_BASE_IMAGE_TAG_SUFFIX}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - SHUFFLE_PASS_WORKER_PROXY=${SHUFFLE_PASS_WORKER_PROXY}
      - SHUFFLE_PASS_APP_PROXY=${SHUFFLE_PASS_APP_PROXY}
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    hostname: shuffle-opensearch
    container_name: shuffle-opensearch
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - bootstrap.memory_lock=true
      - DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI=true
      - cluster.initial_master_nodes=shuffle-opensearch
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.name=shuffle-cluster
      - node.name=shuffle-opensearch
      - node.store.allow_mmap=false
      - discovery.seed_hosts=shuffle-opensearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ${DB_LOCATION}:/usr/share/opensearch/data:z
    ports:
      - 9200:9200
    networks:
      - shuffle
    restart: unless-stopped

  #memcached:
  #  image: docker.io/bitnami/memcached:1
  #  container_name: shuffle-cache
  #  hostname: shuffle-cache
  #  ports:
  #    - 11211:11211

  #docker-socket-proxy:
  #  image: tecnativa/docker-socket-proxy
  #  container_name: docker-socket-proxy
  #  hostname: docker-socket-proxy
  #  privileged: true
  #  environment:
  #    - SERVICES=1
  #    - TASKS=1
  #    - NETWORKS=1
  #    - NODES=1
  #    - BUILD=1
  #    - IMAGES=1
  #    - GRPC=1
  #    - CONTAINERS=1
  #    - PLUGINS=1
  #    - SYSTEM=1
  #    - VOLUMES=1
  #    - INFO=1
  #    - DISTRIBUTION=1
  #    - POST=1
  #    - AUTH=1
  #    - SECRETS=1
  #    - SWARM=1
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  networks:
  #    - shuffle
  #
networks:
  shuffle:
    driver: bridge

    # uncomment to set MTU for swarm mode.
    # MTU should be whatever is your host's preferred MTU is.
    # Refer to this doc to figure out what your host's MTU is:
    # https://shuffler.io/docs/troubleshooting#TLS_timeout_error/Timeout_Errors/EOF_Errors
    # driver_opts:
    #   com.docker.network.driver.mtu: 1460
    ```

**Comment by Im-anhdc** [comment] 2023-11-20 03:11
@0x0elliot As you see, pulling done with opensearch image but error with frontend, orborus, backend.
I used default `.yml` file

**Comment by frikky** [comment] 2023-11-20 12:43
@Im-anhdc I suspect you may have a docker registry already configured that it goes through. Please send the output to this:

`env | grep -i "registry"`

**Comment by Im-anhdc** [comment] 2023-11-20 14:21
hi @0x0elliot,
I tried to pull these images individually but still errors and no result for the command `env | grep -i "registry"`
```shell
Trying to pull repository ghcr.io/shuffle/shuffle-backend ...
Pulling repository ghcr.io/shuffle/shuffle-backend
Error: image shuffle/shuffle-backend:latest not found
[root@localhost ~]# docker pull ghcr.io/shuffle/shuffle-frontend:latest
Trying to pull repository ghcr.io/shuffle/shuffle-frontend ...
Pulling repository ghcr.io/shuffle/shuffle-frontend
Error: image shuffle/shuffle-frontend:latest not found
[root@localhost ~]# docker pull ghcr.io/shuffle/shuffle-orborus:latest
Trying to pull repository ghcr.io/shuffle/shuffle-orborus ...
Pulling repository ghcr.io/shuffle/shuffle-orborus
Error: image shuffle/shuffle-orborus:latest not found
[root@localhost ~]# env | grep -i "registry"
[root@localhost ~]#
```

I also tried to pull the image and it worked:

![image](https://github.com/Shuffle/Shuffle/assets/68783065/9a23b6f0-6d5c-4d6e-b580-15bf701a75a6)

**Comment by Im-anhdc** [comment] 2023-11-20 14:27
It seems to work with docker.io and not with ghcr.io

**Comment by 0x0elliot** [comment] 2023-11-20 14:30
https://stackoverflow.com/questions/74656167/unable-to-pull-image-from-github-container-registry-ghcr can you try thr first solution here for me? @Im-anhdc

**Comment by Im-anhdc** [comment] 2023-11-20 14:41
@0x0elliot I never logged in to Docker before:
```shell
[root@localhost Shuffle]# docker logout ghcr.io
Not logged in to ghcr.io
[root@localhost Shuffle]# docker logout
Not logged in to https://index.docker.io/v1/
[root@localhost Shuffle]# docker pull ghcr.io/shuffle/shuffle-orborus:latest
Trying to pull repository ghcr.io/shuffle/shuffle-orborus ...
Pulling repository ghcr.io/shuffle/shuffle-orborus
Error: image shuffle/shuffle-orborus:latest not found
[root@localhost Shuffle]#
```

**Comment by Im-anhdc** [comment] 2023-11-21 03:37
@0x0elliot I pulled completely the image backend in the repository `ghcr.io/frikky/shuffle-backend`
Could you upload other images to another repository?

```shell
[root@localhost Shuffle]# docker pull ghcr.io/shuffle/shuffle-orborus:1.3.0
Trying to pull repository ghcr.io/shuffle/shuffle-orborus ...
Pulling repository ghcr.io/shuffle/shuffle-orborus
Error: image shuffle/shuffle-orborus:1.3.0 not found
[root@localhost Shuffle]# docker pull ghcr.io/frikky/shuffle-backend:1.1.0
Trying to pull repository ghcr.io/frikky/shuffle-backend ...
1.1.0: Pulling from ghcr.io/frikky/shuffle-backend
c158987b0551: Pull complete
2bea3a8c2c53: Pull complete
bcdac01d8b80: Pull complete
4027ff5c317e: Pull complete
c61b452742c4: Pull complete
6530e6e102e5: Pull complete
15c78737a312: Pull complete
Digest: sha256:7acf157623c32e02635ce72565e56a9d6268b60c773da5fb496cb4660597220d
Status: Downloaded newer image for ghcr.io/frikky/shuffle-backend:1.1.0
```

**Comment by Im-anhdc** [comment] 2023-11-21 07:39
I downloaded Docker Images and loaded it on my shuffle server and it works.
https://linuxhint.com/download-docker-images-for-office-use/
Maybe my Centos server has something wrong.
Thanks for your support!

**Comment by 0x0elliot** [comment] 2023-11-22 10:50
closing this issue for now since we have no control over this behaviour and it wasn't caused by us!

**Closed by 0x0elliot** 2023-11-22 10:50 UTC
Labels: enhancement, backend
