### ISSUE TITLE
Custom SSL / TLS certificate fails to be configured

### ISSUE THREAD

**Issue by ephemeralport** [Shuffle/Shuffle#1012] opened 2023-01-05 15:27 UTC
While attempting to run `sudo ./run.sh` to rebuild the front end, I get an issue with the GitHub Container Registry trying to pull down the nightly image. 

```
...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 125.80s.
Removing intermediate container 14bdc44d6266
 ---> 7054aa014680
Step 8/31 : COPY ./certs /usr/src/app/certs/
 ---> 217d52913db0
Step 9/31 : COPY ./public /usr/src/app/public/
 ---> a8b4959ee76f
Step 10/31 : COPY ./src /usr/src/app/src/
 ---> 75ac6526b883
Step 11/31 : COPY ./*.sh /usr/src/app/
 ---> ba2c74dc159d
Step 12/31 : COPY ./*.json /usr/src/app/
 ---> 37ad40cca4e4
Step 13/31 : RUN rm -rf /usr/src/app/node_modules/webpack
 ---> Running in 7aed33f27618
Removing intermediate container 7aed33f27618
 ---> 0c2d6e69605d
Step 14/31 : RUN yarn build
 ---> Running in 47a45f0459c5
yarn run v1.22.19
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./src/components/ConfigureWorkflow.jsx
TypeError: /usr/src/app/src/components/ConfigureWorkflow.jsx: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got undefined


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build' returned a non-zero code: 1
Error response from daemon: No such image: ghcr.io/frikky/shuffle-frontend:nightly
Starting server
```

I have tried changing the version of the container be pulled from nightly to 1.1.0, but have had no success.

**Comment by frikky** [comment] 2023-01-10 12:23
Hey! This was something one of our devs saw the other day as well, and is probably related to how later Yarn or Babel versions work. 

@dhaval055 do you have any update on it?

**Comment by dhaval055** [comment] 2023-01-10 12:40
> Hey! This was something one of our devs saw the other day as well, and is probably related to how later Yarn or Babel versions work.
> 
> @dhaval055 do you have any update on it?

I think the problem is with babel updates (not 100% sure). The problem is with the declaration of variables using "var" keyword inside for loop. This issue can be attained by replacing all instances of variables declared using "var" with "let".  

For example:- 

Problem:
for (var key in loop) {
     //       
}

Solution:
for (let key in loop) {
     //       
}

**Comment by ephemeralport** [comment] 2023-01-10 17:59
Do I need to replace "var" with "let" in  "ForInStatement" within "ConfigureWorkflow.jsx"?

**Comment by ephemeralport** [comment] 2023-01-10 18:17
No worries! I appreciate your help! Thank you!

**Comment by ephemeralport** [comment] 2023-01-12 15:18
Any update to this?

**Comment by dhaval055** [comment] 2023-01-13 05:30
> Any update to this?

Hi, it is taking longer than expected. We're still working on this. will update soon.

**Comment by ephemeralport** [comment] 2023-01-23 17:04
Sorry to bother, just wondering if there has been any update to this yet. Thanks!

**Comment by ephemeralport** [comment] 2023-01-26 15:43
My issue spawned from downloading the frontend image from GHCR, will this update be pushed to the image so when the rebuild runs it doesn't fail?

**Comment by frikky** [comment] 2023-01-26 18:41
Hey @ephemeralport!

This should only happen if you're trying to re-build Shuffle itself, manually. The image itself should not have this issue, as if it had this issue, it wouldn't be built at all. 

Could you attach a screenshot of what you're seeing?

**Comment by ephemeralport** [comment] 2023-01-27 02:19
I may be missing something, but when running ./run.sh, the rebuild is successful but it still has the default SSL certificate rather than the one I have placed in the certs directory. The files are named the same.

**Comment by yonz2** [comment] 2023-02-06 21:05
Hi,
I'm having the issue as well. I needed to re-install Shuffle and wanted to add my CERTs (were working before). Now, when rebuilding the frontend I get

```
...
yarn run v1.22.19
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./src/components/ConfigureWorkflow.jsx
TypeError: /usr/src/app/src/components/ConfigureWorkflow.jsx: Property left of ForInStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got undefined


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build' returned a non-zero code: 1
```

**Comment by frikky** [comment] 2023-02-07 01:04
Hey @yonz2 and @ephemeralport 

This won't be fixed on the master branch for the time being, as that is typically set for launches of major versions. With that in mind, please try the same thing you're doing on the 1.2.0 branch here and get back to me on the result: https://github.com/Shuffle/Shuffle/tree/1.2.0/frontend

This is where our nightly builds that are released come out of, so I'm sorry if it's a bit rocky to get this up and running now.

The best workaround is probably to skip the rebuild, and [instead to use the section for Nginx reverse proxy we outline](https://shuffler.io/docs/configuration#https)

**Comment by ephemeralport** [comment] 2023-02-22 15:30
Could I possibly get some more detail around the nginx reverse proxy? It's been a major blocker for the last week and the documentation doesn't seem to be getting through to me.

**Comment by ephemeralport** [comment] 2023-02-22 15:31
Specifically when referencing the "nginx.conf" file, is that the one for the system or the nginx.conf file under the conf.d directory?

**Comment by frikky** [comment] 2023-02-22 16:01
> Could I possibly get some more detail around the nginx reverse proxy? It's been a major blocker for the last week and the documentation doesn't seem to be getting through to me.

Sorry about that. I've updated it a bit to reflect your questions. Does this clarify it?

https://github.com/Shuffle/Shuffle-docs/blob/master/docs/configuration.md#using-the-nginx-reverse-proxy-for-tlsssl

**Comment by ephemeralport** [comment] 2023-02-22 16:46
You're okay! I was reading over the docker logs when the app is being brought up and it appears to demo certificates override everything. Even with the demo certificates removed from the certs/ directory, it still uses them and I am unsure why.  The application does not appear to recognize the reverse proxy nor self-signed certificates created besides the default demo certificates.

` ### (Ignore the SSL certificate warning because we installed self-signed demo certificates)`

**Comment by frikky** [comment] 2023-02-22 17:17
> You're okay! I was reading over the docker logs when the app is being brought up and it appears to demo certificates override everything. Even with the demo certificates removed from the certs/ directory, it still uses them and I am unsure why. The application does not appear to recognize the reverse proxy nor self-signed certificates created besides the default demo certificates.
> 
> ` ### (Ignore the SSL certificate warning because we installed self-signed demo certificates)`

What port did you set up your local nginx for? And are you making sure to connect to that port instead of 3001 or 3443? My suggestion is to connect it like this:
- User/API -> nginx:443 -> shuffle-frontend:3001

This way, when you're trying to use shuffle, you can just connect to port 443, both for the frontend and backend, and you can further make ports 3001/3443/5001 only available on the server itself, not exposed.

**Comment by ephemeralport** [comment] 2023-02-22 17:18
I am happy to report that the issue was actually on my end, helps if you check your AWS Security Group rules when conducting testing. Thank you for your help with this! I believe this issue can be resolved!

**Closed** 2023-02-26 22:50 UTC
Labels: bug, 1.2.0
