### ISSUE TITLE
[BUG] Let's break orgs and suborgs an pretty much all users :p

### ISSUE THREAD

**Issue by azgaviperr** [Shuffle/Shuffle#940] opened 2022-09-27 15:29 UTC
**Describe the bug**
When we log into Shuffle, there is a Windows that ask to name your organisation and users status etc.

Even if the informations where already setup by someone else (except user name and role ...)

If a user change the name of the organisation (maybe due to special characters) then all link get broken. 

SSO doesn't show up on login page, and all capacity to move in between orgs disapear. (the break happen after restart of the stack)

Normal situation: 

![image](https://user-images.githubusercontent.com/7451354/192566356-b93b1e44-aa17-47a6-bd0f-ad7b1a396a13.png)
![image](https://user-images.githubusercontent.com/7451354/192566572-bef8935b-1bb1-4970-ab9d-f437b84f9d14.png)

When things go brown color

![image](https://user-images.githubusercontent.com/7451354/192568692-1a4757cb-25ed-4030-a215-e4573687fc3d.png)

Login is very long to get through and there is no more capacity to switch to suborgs

**Comment by frikky** [comment] 2022-09-27 19:43
What in the world? This looks like a  problem with retrieving information from opensearch then, no?

I'm assuming the 503 is somehow related to Opensearch indexes getting broken.

Could you share some logs from these places when you try to login / see the org dropdown:
- The backend container
- The opensearch container
- The console in your browser (for potential frontend issues)

Cheers!

**Comment by frikky** [comment] 2023-10-05 10:01
Closing, as this was never reproduced, and we've fixed tons of ~related issues since then.

**Closed by frikky** 2023-10-05 10:01 UTC
Labels: bug
